# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- test

pool:
  vmImage: windows-latest

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  solution: "NiN3KOdeAPI.sln"

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: dir
    - script: dir NiN3KodeAPI
    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Test(2e1858b1-de46-4865-a290-c1d54976a10f)'
        appType: 'webAppContainer'
        WebAppName: 'adb-test-nin3-as'
        DockerRepository: 'NiN3KodeAPI'
        DockerImageTag: '$(tag)'