# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- test

pool:
  vmImage: windows-latest

resources:
- repo: self

variables:
  solution: "**/NiN3KOdeAPI.sln"
  buildConfiguration: 'Test'

steps: 

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: MSBuild@1
  inputs: 
    solution: '$(solution)'
    msbuildArchitecture: x64
    configuration: '$(buildConfiguration)'
    msbuildArguments: '' 