# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- test

pool:
  vmImage: windows-latest

resources:
- repo: self

variables:
  solution: '**/NiN3KodeAPI.sln'
  buildConfiguration: 'Test'

steps: 

- task: CmdLine@2
  inputs:
    script: |
     call dotnet restore $(solution)
     dotnet build $(solution)

- task: ArchiveFiles@2
  name: NiN3Kodeapi    
  inputs:
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/NiN3Kodeapi.zip' 
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs: 
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'Nin3Kodeapi'
    publishLocation: Container