# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- test

pool:
  vmImage: windows-latest

resources:
- repo: self

variables:
  solution: '**/NiN3KOdeAPI.sln'
  buildConfiguration: 'Test'
  project: 'NiN3KodeAPI/NiN3KodeAPI.csproj'

steps: 

- task: CmdLine@2
  inputs:
    script: |
     call dotnet restore $(project)
     dotnet build $(project) -c Release -o /app/build
