# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- test

pool:
  vmImage: windows-latest

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  solution: "NiN3KOdeAPI.sln"

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub'
        repository: 'artsdatabanken/nin3kodeapi'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: '$(Build.SourceBranchName)'

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Test(2e1858b1-de46-4865-a290-c1d54976a10f)'
        appType: 'webAppContainer'
        WebAppName: 'adb-test-ao3-wp-as'
        DockerNamespace: 'artsdatabanken/nin3kodeapi'
        DockerRepository: 'artsdatabanken/nin3kodeapi'
        DockerImageTag: 'test'
        StartupCommand: 'dotnet NiN3KodeAPI.dll'