# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- test

pool:
  vmImage: windows-latest

resources:
- repo: self

variables:
  solution: 'NiN3KodeAPI.sln'
  buildConfiguration: 'Test'

steps: 

# - task: CmdLine@2
#   inputs:
#     script: |
#      call mkdir build
#      call dotnet restore $(solution)
#      call dotnet build $(solution) -o build

- task: DotNetCoreCLI@2
  displayName: 'Publish and zip'
  inputs:
    command: publish
    publishWebProjects: False
    projects: $(solution)
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

# - task: ArchiveFiles@2
#   name: NiN3Kodeapi    
#   inputs:
#     includeRootFolder: false
#     rootFolderOrFile: build
#     archiveType: 'zip'
#     archiveFile: '$(Build.ArtifactStagingDirectory)/NiN3Kodeapi.zip' 
#     replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs: 
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'Nin3Kodeapi'
    publishLocation: Container