# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- test

pool:
  vmImage: windows-latest

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  solution: "NiN3KOdeAPI.sln"

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: dir
    - script: dir NiN3KodeAPI
    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: Bash@3
      displayName: Save Docker Image
      inputs:
        targetType: 'inline'
        script: |
          docker save ninkode3:$(tag) -o $(Pipeline.Workspace)/ninkode3api.tar