// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NiN3KodeAPI.DbContexts;

#nullable disable

namespace NiN3KodeAPI.Migrations
{
    [DbContext(typeof(NiN3DbContext))]
    [Migration("20230515142205_variabelgruppe")]
    partial class variabelgruppe
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.15");

            modelBuilder.Entity("NiN3KodeAPI.Entities.Domene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Domene");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f5ba9df1-de9a-40de-b36d-81a99653312b"),
                            Navn = "3.0"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Grunntype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Delkode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HovedtypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProsedyrekategoriId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HovedtypeId");

                    b.HasIndex("ProsedyrekategoriId");

                    b.HasIndex("VersionId");

                    b.ToTable("Grunntype");
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Hovedtype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Delkode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HovedtypegruppeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProsedyrekategoriId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HovedtypegruppeId");

                    b.HasIndex("ProsedyrekategoriId");

                    b.HasIndex("VersionId");

                    b.ToTable("Hovedtype");
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Hovedtypegruppe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Delkode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Typekategori2Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Typekategori2Id");

                    b.HasIndex("VersionId");

                    b.ToTable("Hovedtypegruppe");
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Lookupdata.Ecosystnivaa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ecosystnivaa");

                    b.HasData(
                        new
                        {
                            Id = new Guid("941b5dda-cbbe-4416-9e3b-a2ccbe7fd769"),
                            Beskrivelse = "abiotisk",
                            Kode = "A"
                        },
                        new
                        {
                            Id = new Guid("9b6dcc36-eeaa-4283-bc6d-fbb1863d487f"),
                            Beskrivelse = "biotisk",
                            Kode = "B"
                        },
                        new
                        {
                            Id = new Guid("d3b0dcbe-3689-4bb1-b30d-d1a4c41fdaa2"),
                            Beskrivelse = "økodiversitet",
                            Kode = "C"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Lookupdata.Maalestokk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Maalestokk");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae1fd731-2bf7-4956-8da4-cc0203e0779e"),
                            Beskrivelse = "grunntype",
                            Kode = "G"
                        },
                        new
                        {
                            Id = new Guid("11061cd1-90f7-47ae-b3ba-21c74d0a0153"),
                            Beskrivelse = "kartleggingsenhet tilpasset 1:5000",
                            Kode = "005K"
                        },
                        new
                        {
                            Id = new Guid("ab332908-eefe-4ed2-99ef-49dab60bed11"),
                            Beskrivelse = "kartleggingsenhet tilpasset 1:10 000",
                            Kode = "010K"
                        },
                        new
                        {
                            Id = new Guid("428ed318-7b13-4768-96ae-a7479cec4168"),
                            Beskrivelse = "kartleggingsenhet tilpasset 1:20 000",
                            Kode = "020K"
                        },
                        new
                        {
                            Id = new Guid("68f43148-edf9-4e1d-993c-9b6ade23f775"),
                            Beskrivelse = "kartleggingsenhet tilpasset 1:50 000",
                            Kode = "050K"
                        },
                        new
                        {
                            Id = new Guid("be5677f2-ad34-4459-b064-051f253d7339"),
                            Beskrivelse = "kartleggingsenhet tilpasset 1:100 000",
                            Kode = "100K"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Lookupdata.Prosedyrekategori", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Prosedyrekategori");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b0ec1ca-8f37-4ccc-8280-913ab544a5ff"),
                            Beskrivelse = "A",
                            Kode = "A"
                        },
                        new
                        {
                            Id = new Guid("94b7a9c8-1a7d-483c-9390-c9b346efe469"),
                            Beskrivelse = "B",
                            Kode = "B"
                        },
                        new
                        {
                            Id = new Guid("384aeddb-54a4-4236-a4f9-7330fa8666b6"),
                            Beskrivelse = "C",
                            Kode = "C"
                        },
                        new
                        {
                            Id = new Guid("9dec75fa-b6eb-4596-ad6d-7995e38b1944"),
                            Beskrivelse = "D",
                            Kode = "D"
                        },
                        new
                        {
                            Id = new Guid("296e5ebd-11fb-4559-a252-d14a57926bac"),
                            Beskrivelse = "E",
                            Kode = "E"
                        },
                        new
                        {
                            Id = new Guid("f76f3e2b-bbd6-43bd-aed0-6f4bcb40c4ac"),
                            Beskrivelse = "F",
                            Kode = "F"
                        },
                        new
                        {
                            Id = new Guid("75cd215d-ef92-47fd-9383-518c5d9db002"),
                            Beskrivelse = "G",
                            Kode = "G"
                        },
                        new
                        {
                            Id = new Guid("eb93d97c-20a2-44ab-8d90-f34260e864f1"),
                            Beskrivelse = "H",
                            Kode = "H"
                        },
                        new
                        {
                            Id = new Guid("314f4aed-88db-46bd-82fd-be1409fe30b3"),
                            Beskrivelse = "I",
                            Kode = "I"
                        },
                        new
                        {
                            Id = new Guid("23b34728-1eaf-4358-8023-8127c5f3a9f0"),
                            Beskrivelse = "J",
                            Kode = "J"
                        },
                        new
                        {
                            Id = new Guid("c5c7f807-b8f8-4ca2-b6a3-630b72e672fb"),
                            Beskrivelse = "K",
                            Kode = "K"
                        },
                        new
                        {
                            Id = new Guid("b4d32f82-58c9-49f0-9ea9-020f229b2e8f"),
                            Beskrivelse = "L",
                            Kode = "L"
                        },
                        new
                        {
                            Id = new Guid("9d16c459-7a8a-4b9a-ac8b-c7b180150ab6"),
                            Beskrivelse = "M",
                            Kode = "M"
                        },
                        new
                        {
                            Id = new Guid("17f7a898-9114-4a12-995b-912ac9620054"),
                            Beskrivelse = "N",
                            Kode = "N"
                        },
                        new
                        {
                            Id = new Guid("25281fab-d33a-47da-b21f-eba772e762e8"),
                            Beskrivelse = "O",
                            Kode = "O"
                        },
                        new
                        {
                            Id = new Guid("78a321a6-1667-4f97-b314-6b37ce980758"),
                            Beskrivelse = "Ikke angitt",
                            Kode = "0"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Lookupdata.Typekategori", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Typekategori");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5432c6b2-7afe-4e40-9812-1d06b2d1699d"),
                            Beskrivelse = "livsmedium",
                            Kode = "LI"
                        },
                        new
                        {
                            Id = new Guid("5bbb768c-ffb9-44a5-9f4d-7d48ebdfe336"),
                            Beskrivelse = "landformvariasjon",
                            Kode = "LV"
                        },
                        new
                        {
                            Id = new Guid("8f87d5eb-ba1d-487d-b037-3d1a316d743d"),
                            Beskrivelse = "marine vannmasser",
                            Kode = "MV"
                        },
                        new
                        {
                            Id = new Guid("0ca5b7b4-224a-44a5-9bc0-d6f2d9ffe257"),
                            Beskrivelse = "primært økodiversitetsnivå",
                            Kode = "PE"
                        },
                        new
                        {
                            Id = new Guid("802a52c4-15a4-4d16-a474-624a2de7f693"),
                            Beskrivelse = "sekundært økodiversitetsnivå",
                            Kode = "SE"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Lookupdata.Typekategori2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Typekategori2");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e340153-1548-4619-8b45-9ebdf5d1394c"),
                            Beskrivelse = "bremassiv",
                            Kode = "BM"
                        },
                        new
                        {
                            Id = new Guid("0073c05e-ef0e-41ba-9cf1-c2e6a48454b0"),
                            Beskrivelse = "elveløp",
                            Kode = "EL"
                        },
                        new
                        {
                            Id = new Guid("f6276f3f-aa2d-4cfe-893a-997fbd565a01"),
                            Beskrivelse = "landformer i fast fjell og løsmasser",
                            Kode = "FL"
                        },
                        new
                        {
                            Id = new Guid("8f299742-a6a0-4975-b9ab-36a96f4b6ee3"),
                            Beskrivelse = "innsjøbasseng",
                            Kode = "IB"
                        },
                        new
                        {
                            Id = new Guid("8d8456e8-9d9e-4eff-ae34-7143ed00eea6"),
                            Beskrivelse = "landskapstype",
                            Kode = "LA"
                        },
                        new
                        {
                            Id = new Guid("2a84ff69-2c91-4b82-878e-b63ed66fcd0a"),
                            Beskrivelse = "natursystem",
                            Kode = "NA"
                        },
                        new
                        {
                            Id = new Guid("b511bf09-13f5-48fa-b295-44423da97a8f"),
                            Beskrivelse = "naturkompleks",
                            Kode = "NK"
                        },
                        new
                        {
                            Id = new Guid("ba5695fb-e754-44b4-8434-59ef8be76c94"),
                            Beskrivelse = "torvmarksmassiv",
                            Kode = "TM"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Lookupdata.Typekategori3", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Typekategori3");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fca564d6-005c-4cdd-ade0-0e1322be6261"),
                            Beskrivelse = "vannmassesystemer",
                            Kode = "VM"
                        },
                        new
                        {
                            Id = new Guid("f4034d7d-f392-45ba-b3fd-09f0916951b3"),
                            Beskrivelse = "mark- og bunnsystemer",
                            Kode = "MB"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Lookupdata.Variabelgruppe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Variabelgruppe");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7c241c3c-b3b9-4b02-b7bc-792f241b0299"),
                            Beskrivelse = "W W",
                            Kode = "W W"
                        },
                        new
                        {
                            Id = new Guid("a9cfd4b9-65df-4acf-9cb6-bd4676c5c330"),
                            Beskrivelse = "EE elveløpsegenskaper",
                            Kode = "EE elveløpsegenskaper"
                        },
                        new
                        {
                            Id = new Guid("081c0087-ef48-4b8e-bfca-51e796578ee8"),
                            Beskrivelse = "SB skogbruksrelaterte egeskaper",
                            Kode = "SB skogbruksrelaterte egeskaper"
                        },
                        new
                        {
                            Id = new Guid("1ec448ec-256e-404e-9dfd-6fadc492250b"),
                            Beskrivelse = "DL liggende død ved (læger)",
                            Kode = "DL liggende død ved (læger)"
                        },
                        new
                        {
                            Id = new Guid("69d3075b-39f4-457b-8124-075fc7a84eeb"),
                            Beskrivelse = "W artsforekomst/-mengde",
                            Kode = "W artsforekomst/-mengde"
                        },
                        new
                        {
                            Id = new Guid("55f04db9-eca0-4245-a80d-4eb56737ffaf"),
                            Beskrivelse = "AG artsgruppesammensetning",
                            Kode = "AG artsgruppesammensetning"
                        },
                        new
                        {
                            Id = new Guid("ce1df305-5517-4471-b4c7-89ba16a33683"),
                            Beskrivelse = "AR relativ del-artsgruppesammensetning",
                            Kode = "AR relativ del-artsgruppesammensetning"
                        },
                        new
                        {
                            Id = new Guid("5168f34c-2260-4ee7-a82d-e0488b521b91"),
                            Beskrivelse = "BO naturgitte breobjekter",
                            Kode = "BO naturgitte breobjekter"
                        },
                        new
                        {
                            Id = new Guid("f26b8a7b-0ec5-47e9-82db-3925e4a42dd9"),
                            Beskrivelse = "EB elvebanker",
                            Kode = "EB elvebanker"
                        },
                        new
                        {
                            Id = new Guid("e3e553f4-f52f-4885-bcd8-e134fc1e75f8"),
                            Beskrivelse = "EO andre naturgitte elveløpsobjekter",
                            Kode = "EO andre naturgitte elveløpsobjekter"
                        },
                        new
                        {
                            Id = new Guid("f3ed0009-2dea-4617-a226-aae42f810804"),
                            Beskrivelse = "IO naturgitte innsjøobjekter",
                            Kode = "IO naturgitte innsjøobjekter"
                        },
                        new
                        {
                            Id = new Guid("51a1da49-4c04-4b38-bbe2-c647ab74b3a4"),
                            Beskrivelse = "TA torvmarksmassiv: myrsegment",
                            Kode = "TA torvmarksmassiv: myrsegment"
                        },
                        new
                        {
                            Id = new Guid("4dbba74b-d00b-4d03-8fe7-95ab5928ae18"),
                            Beskrivelse = "TB torvmarksmassiv: myrstruktur",
                            Kode = "TB torvmarksmassiv: myrstruktur"
                        },
                        new
                        {
                            Id = new Guid("7657a33f-89bd-4921-ba09-ed890eb7b1ac"),
                            Beskrivelse = "TC torvmarksmassiv: mikrostruktur",
                            Kode = "TC torvmarksmassiv: mikrostruktur"
                        },
                        new
                        {
                            Id = new Guid("c6e52333-0f9c-4f81-bbd3-705110166df3"),
                            Beskrivelse = "SE skogegenskaper",
                            Kode = "SE skogegenskaper"
                        },
                        new
                        {
                            Id = new Guid("f02e1909-7b92-4aaf-8166-03d1a61b55b5"),
                            Beskrivelse = "IE innsjøbassengegenskaper",
                            Kode = "IE innsjøbassengegenskaper"
                        },
                        new
                        {
                            Id = new Guid("32af0b61-1f2a-4a22-bf29-d3c77a5d2a8c"),
                            Beskrivelse = "GE generelle egenskaper",
                            Kode = "GE generelle egenskaper"
                        },
                        new
                        {
                            Id = new Guid("2d32d816-e800-4feb-a63e-0161ccf1306c"),
                            Beskrivelse = "GT generelle terrengegenskaper",
                            Kode = "GT generelle terrengegenskaper"
                        },
                        new
                        {
                            Id = new Guid("d4920d25-db38-4886-bd5f-19c32996924a"),
                            Beskrivelse = "HE havegenskaper",
                            Kode = "HE havegenskaper"
                        },
                        new
                        {
                            Id = new Guid("d746bcf0-1e55-48ad-92b5-45c472f40caa"),
                            Beskrivelse = "BE bremassivegenskaper",
                            Kode = "BE bremassivegenskaper"
                        },
                        new
                        {
                            Id = new Guid("cbe8a960-443d-4ce9-affd-b997b1d8019d"),
                            Beskrivelse = "OE menneskeskapt objekt i elv",
                            Kode = "OE menneskeskapt objekt i elv"
                        },
                        new
                        {
                            Id = new Guid("7989f5ea-799f-44e9-aece-6fcb33f5a7af"),
                            Beskrivelse = "OI menneskeskapt objekt i innsjø eller til havs",
                            Kode = "OI menneskeskapt objekt i innsjø eller til havs"
                        },
                        new
                        {
                            Id = new Guid("6246513c-094b-4c70-bb8b-467924bfb2b2"),
                            Beskrivelse = "OT menneskeskapt terrestrisk objekt",
                            Kode = "OT menneskeskapt terrestrisk objekt"
                        },
                        new
                        {
                            Id = new Guid("38c83231-e099-4d2a-bf68-79cc7dcaf73f"),
                            Beskrivelse = "SU suksesjonsrelaterte egenskaper",
                            Kode = "SU suksesjonsrelaterte egenskaper"
                        },
                        new
                        {
                            Id = new Guid("b0ce8ee1-a871-4a0f-8d46-6a5a1cfef259"),
                            Beskrivelse = "JB jordbruksrelaterte egenskaper",
                            Kode = "JB jordbruksrelaterte egenskaper"
                        },
                        new
                        {
                            Id = new Guid("13620de7-a51d-49a7-ac09-bc2ab0605270"),
                            Beskrivelse = "SB skogbruksrelaterte egenskaper",
                            Kode = "SB skogbruksrelaterte egenskaper"
                        },
                        new
                        {
                            Id = new Guid("655fb8c1-8be1-45d6-a8ed-8e6d357d4eeb"),
                            Beskrivelse = "SB skogbruksegenskaper",
                            Kode = "SB skogbruksegenskaper"
                        },
                        new
                        {
                            Id = new Guid("d0f9f516-ef15-43a4-add6-19e02a1e9df7"),
                            Beskrivelse = "DG stående død ved (gadder)",
                            Kode = "DG stående død ved (gadder)"
                        },
                        new
                        {
                            Id = new Guid("cf9bc9e2-40bd-4a94-8fde-d1a2c8639026"),
                            Beskrivelse = "DR relativ sammensetning av død ved",
                            Kode = "DR relativ sammensetning av død ved"
                        },
                        new
                        {
                            Id = new Guid("621f89e7-ae64-40a6-9f64-fd626b330eca"),
                            Beskrivelse = "TE generelle treegenskaper",
                            Kode = "TE generelle treegenskaper"
                        },
                        new
                        {
                            Id = new Guid("4ca7d75b-58e8-47ef-b9ad-9ba682a2e782"),
                            Beskrivelse = "TG gammelt tre",
                            Kode = "TG gammelt tre"
                        },
                        new
                        {
                            Id = new Guid("bc086a2c-c14b-4da1-b3e9-02a5e55ecc71"),
                            Beskrivelse = "TL tre med spesielt livsmedium",
                            Kode = "TL tre med spesielt livsmedium"
                        },
                        new
                        {
                            Id = new Guid("d8f460ee-4a4e-4f27-be2f-51eeb99901a9"),
                            Beskrivelse = "TM trær med gitt minstestørrelse",
                            Kode = "TM trær med gitt minstestørrelse"
                        },
                        new
                        {
                            Id = new Guid("a2869a72-b2e9-4f41-83a4-da6f882243ca"),
                            Beskrivelse = "TS trær med gitt størrelse",
                            Kode = "TS trær med gitt størrelse"
                        },
                        new
                        {
                            Id = new Guid("3058b2a4-b467-4c9c-bc36-22ccf2541930"),
                            Beskrivelse = "AM artsforekomst/-mengde",
                            Kode = "AM artsforekomst/-mengde"
                        },
                        new
                        {
                            Id = new Guid("841cc039-3c64-45da-80ba-1ac94edf15bb"),
                            Beskrivelse = "FA fremmedartsegenskaper",
                            Kode = "FA fremmedartsegenskaper"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Lookupdata.Variabelkategori", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Variabelkategori");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d62830da-ffd4-44f3-97af-e5c6f9649ef8"),
                            Beskrivelse = "mennekebetinget",
                            Kode = "M"
                        },
                        new
                        {
                            Id = new Guid("4ea06d5e-542b-48f2-9fda-843d6331b38b"),
                            Beskrivelse = "naturgitt",
                            Kode = "N"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Lookupdata.Variabelkategori2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Variabelkategori2");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5cb204ee-5feb-4050-9d7a-548b9fcad080"),
                            Beskrivelse = "artssammensetningsdynamikk",
                            Kode = "AD"
                        },
                        new
                        {
                            Id = new Guid("29e08dee-7c4a-4269-b3f9-5b6b9d76e0c2"),
                            Beskrivelse = "bergarter",
                            Kode = "BE"
                        },
                        new
                        {
                            Id = new Guid("afb433e8-44a1-45ad-a5d2-2a6c00f79bff"),
                            Beskrivelse = "korttidsmiljøvariabel",
                            Kode = "KM"
                        },
                        new
                        {
                            Id = new Guid("74d61a6f-c714-4c96-8701-dfacc0b1aaee"),
                            Beskrivelse = "lokal miljøvariabel",
                            Kode = "LM"
                        },
                        new
                        {
                            Id = new Guid("08a998da-1963-40b8-bd48-8922f9e680bb"),
                            Beskrivelse = "landform-objekter",
                            Kode = "LO"
                        },
                        new
                        {
                            Id = new Guid("a8a63710-0477-432f-af80-ee6f8d045523"),
                            Beskrivelse = "miljødynamikk",
                            Kode = "MD"
                        },
                        new
                        {
                            Id = new Guid("c267dcd0-16f9-48e0-925a-d4c3a5988571"),
                            Beskrivelse = "menneskeskapt objekt",
                            Kode = "MO"
                        },
                        new
                        {
                            Id = new Guid("1213fd0f-10a2-431a-9de2-33872e774fc8"),
                            Beskrivelse = "naturgitt objekt",
                            Kode = "NO"
                        },
                        new
                        {
                            Id = new Guid("df2a28e2-3f54-4391-9d56-73e5ca54dd9c"),
                            Beskrivelse = "romlig artsfordelingsmønster",
                            Kode = "RA"
                        },
                        new
                        {
                            Id = new Guid("9be0bbf9-7478-49e5-a498-9f65eb71ce90"),
                            Beskrivelse = "regional miljøvariabel",
                            Kode = "RM"
                        },
                        new
                        {
                            Id = new Guid("7b459aeb-1023-4810-be3f-4094191756af"),
                            Beskrivelse = "romlig strukturvariasjon",
                            Kode = "RS"
                        },
                        new
                        {
                            Id = new Guid("9ea3a365-f4fd-4f3e-940f-384e8b9c218f"),
                            Beskrivelse = "strukturerende og funksjonelle artsgrupper",
                            Kode = "SA"
                        },
                        new
                        {
                            Id = new Guid("d39933e6-4aff-4a5f-a818-23fc716ca06f"),
                            Beskrivelse = "terrengformvariasjon",
                            Kode = "TF"
                        },
                        new
                        {
                            Id = new Guid("2ad45eb2-722d-46fa-a863-c640f94c1756"),
                            Beskrivelse = "vertikal struktur",
                            Kode = "VS"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Lookupdata.Variabeltype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Variabeltype");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6757587-d072-4aeb-bccc-8a6ab6f0ceba"),
                            Beskrivelse = "enkel, ikke-ordnet faktorvariabel",
                            Kode = "FE"
                        },
                        new
                        {
                            Id = new Guid("b6fa1f07-03b7-4210-a8ae-de960edf0e41"),
                            Beskrivelse = "kompleks, ikke-ordnet faktorvariabel",
                            Kode = "FK"
                        },
                        new
                        {
                            Id = new Guid("9b0dba26-b5ee-4bce-a4ad-5716ec274620"),
                            Beskrivelse = "enkel gradient",
                            Kode = "GE"
                        },
                        new
                        {
                            Id = new Guid("c1fb504d-c22c-42d5-b20b-6e1dbcff7ce7"),
                            Beskrivelse = "kompleks gradient",
                            Kode = "GK"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Type", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EcosystnivaaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Typekategori2Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TypekategoriId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EcosystnivaaId");

                    b.HasIndex("Typekategori2Id");

                    b.HasIndex("TypekategoriId");

                    b.HasIndex("VersionId");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Undertype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GrunntypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GrunntypeId");

                    b.HasIndex("VersionId");

                    b.ToTable("Undertype");
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Grunntype", b =>
                {
                    b.HasOne("NiN3KodeAPI.Entities.Hovedtype", "Hovedtype")
                        .WithMany()
                        .HasForeignKey("HovedtypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NiN3KodeAPI.Entities.Lookupdata.Prosedyrekategori", "Prosedyrekategori")
                        .WithMany()
                        .HasForeignKey("ProsedyrekategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NiN3KodeAPI.Entities.Domene", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hovedtype");

                    b.Navigation("Prosedyrekategori");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Hovedtype", b =>
                {
                    b.HasOne("NiN3KodeAPI.Entities.Hovedtypegruppe", "Hovedtypegruppe")
                        .WithMany()
                        .HasForeignKey("HovedtypegruppeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NiN3KodeAPI.Entities.Lookupdata.Prosedyrekategori", "Prosedyrekategori")
                        .WithMany()
                        .HasForeignKey("ProsedyrekategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NiN3KodeAPI.Entities.Domene", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hovedtypegruppe");

                    b.Navigation("Prosedyrekategori");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Hovedtypegruppe", b =>
                {
                    b.HasOne("NiN3KodeAPI.Entities.Lookupdata.Typekategori2", "Typekategori2")
                        .WithMany()
                        .HasForeignKey("Typekategori2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NiN3KodeAPI.Entities.Domene", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Typekategori2");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Type", b =>
                {
                    b.HasOne("NiN3KodeAPI.Entities.Lookupdata.Ecosystnivaa", "Ecosystnivaa")
                        .WithMany()
                        .HasForeignKey("EcosystnivaaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NiN3KodeAPI.Entities.Lookupdata.Typekategori2", "Typekategori2")
                        .WithMany()
                        .HasForeignKey("Typekategori2Id");

                    b.HasOne("NiN3KodeAPI.Entities.Lookupdata.Typekategori", "Typekategori")
                        .WithMany()
                        .HasForeignKey("TypekategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NiN3KodeAPI.Entities.Domene", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ecosystnivaa");

                    b.Navigation("Typekategori");

                    b.Navigation("Typekategori2");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Undertype", b =>
                {
                    b.HasOne("NiN3KodeAPI.Entities.Grunntype", "Grunntype")
                        .WithMany()
                        .HasForeignKey("GrunntypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NiN3KodeAPI.Entities.Domene", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grunntype");

                    b.Navigation("Version");
                });
#pragma warning restore 612, 618
        }
    }
}
