// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NiN3KodeAPI.DbContexts;

#nullable disable

namespace NiN3KodeAPI.Migrations
{
    [DbContext(typeof(NiN3DbContext))]
    partial class NiN3DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.15");

            modelBuilder.Entity("NiN3KodeAPI.Entities.Domene", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Domene");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c7eec7d9-b13e-406c-aa3b-3b198adb41aa"),
                            Navn = "3.0"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Grunntype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Delkode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HovedtypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProsedyrekategoriId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HovedtypeId");

                    b.HasIndex("ProsedyrekategoriId");

                    b.HasIndex("VersionId");

                    b.ToTable("Grunntype");
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Hovedtype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Delkode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HovedtypegruppeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProsedyrekategoriId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HovedtypegruppeId");

                    b.HasIndex("ProsedyrekategoriId");

                    b.HasIndex("VersionId");

                    b.ToTable("Hovedtype");
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Hovedtypegruppe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Delkode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Typekategori2Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Typekategori2Id");

                    b.HasIndex("VersionId");

                    b.ToTable("Hovedtypegruppe");
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Lookupdata.Ecosystnivaa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ecosystnivaa");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96b20e46-a278-44c1-9e3e-8abb9932be94"),
                            Beskrivelse = "abiotisk",
                            Kode = "A"
                        },
                        new
                        {
                            Id = new Guid("0fec972d-77b0-426f-91a0-df4d17dd3dbe"),
                            Beskrivelse = "biotisk",
                            Kode = "B"
                        },
                        new
                        {
                            Id = new Guid("b55b37b4-2ea0-4f28-b1c5-c1aee6c61214"),
                            Beskrivelse = "økodiversitet",
                            Kode = "C"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Lookupdata.Maalestokk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Maalestokk");

                    b.HasData(
                        new
                        {
                            Id = new Guid("089c7579-e025-41cd-a035-5e546d82568e"),
                            Beskrivelse = "grunntype",
                            Kode = "G"
                        },
                        new
                        {
                            Id = new Guid("6f8c8872-d333-407c-957d-279cc89c6158"),
                            Beskrivelse = "kartleggingsenhet tilpasset 1:5000",
                            Kode = "005K"
                        },
                        new
                        {
                            Id = new Guid("f1cbec47-1ab7-429d-9300-bd9762011ff1"),
                            Beskrivelse = "kartleggingsenhet tilpasset 1:10 000",
                            Kode = "010K"
                        },
                        new
                        {
                            Id = new Guid("e4296af2-40f4-43c4-9511-5f3b644ce0fc"),
                            Beskrivelse = "kartleggingsenhet tilpasset 1:20 000",
                            Kode = "020K"
                        },
                        new
                        {
                            Id = new Guid("97eddcd8-ca72-4c96-a5af-79e5f5a8ddaa"),
                            Beskrivelse = "kartleggingsenhet tilpasset 1:50 000",
                            Kode = "050K"
                        },
                        new
                        {
                            Id = new Guid("8125ce97-80ab-4558-bb82-99c8c0c62fd9"),
                            Beskrivelse = "kartleggingsenhet tilpasset 1:100 000",
                            Kode = "100K"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Lookupdata.Prosedyrekategori", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Prosedyrekategori");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d82e90f3-ce71-46e9-87ef-845a295c8235"),
                            Beskrivelse = "A",
                            Kode = "A"
                        },
                        new
                        {
                            Id = new Guid("add2f130-5ba5-4b66-81e4-d8f7fd323bbd"),
                            Beskrivelse = "B",
                            Kode = "B"
                        },
                        new
                        {
                            Id = new Guid("f95841ab-8a63-451e-b474-fd0020a85b60"),
                            Beskrivelse = "C",
                            Kode = "C"
                        },
                        new
                        {
                            Id = new Guid("c38dd757-b54e-4df4-9dc7-c01f579b9e9a"),
                            Beskrivelse = "D",
                            Kode = "D"
                        },
                        new
                        {
                            Id = new Guid("054c7941-1064-4a15-b12d-406ed982dafe"),
                            Beskrivelse = "E",
                            Kode = "E"
                        },
                        new
                        {
                            Id = new Guid("e0132d0c-f315-4ceb-b59c-54c3a524d66b"),
                            Beskrivelse = "F",
                            Kode = "F"
                        },
                        new
                        {
                            Id = new Guid("d98dcc37-46b0-480d-9c11-11145fb2a548"),
                            Beskrivelse = "G",
                            Kode = "G"
                        },
                        new
                        {
                            Id = new Guid("263da5c0-868c-4e9d-8d80-bf076a76137a"),
                            Beskrivelse = "H",
                            Kode = "H"
                        },
                        new
                        {
                            Id = new Guid("05bb298a-2b05-4c03-8fae-868f3611bff9"),
                            Beskrivelse = "I",
                            Kode = "I"
                        },
                        new
                        {
                            Id = new Guid("4db99215-08af-4b7a-a045-da827951e46c"),
                            Beskrivelse = "J",
                            Kode = "J"
                        },
                        new
                        {
                            Id = new Guid("9dfa8a3c-e6b5-4d61-8c7b-59e39d589906"),
                            Beskrivelse = "K",
                            Kode = "K"
                        },
                        new
                        {
                            Id = new Guid("28a16dac-0aa0-4705-afb7-d294e9846271"),
                            Beskrivelse = "L",
                            Kode = "L"
                        },
                        new
                        {
                            Id = new Guid("d80479bf-f693-4fc3-a799-b39aa512b900"),
                            Beskrivelse = "M",
                            Kode = "M"
                        },
                        new
                        {
                            Id = new Guid("be81020b-74c9-4500-beda-f2f9938132ad"),
                            Beskrivelse = "N",
                            Kode = "N"
                        },
                        new
                        {
                            Id = new Guid("b7aaac85-b733-45ab-ba2d-e6f18c3180ae"),
                            Beskrivelse = "O",
                            Kode = "O"
                        },
                        new
                        {
                            Id = new Guid("b9aa37b7-c6d1-40d8-bc57-3150d3001106"),
                            Beskrivelse = "Ikke angitt",
                            Kode = "0"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Lookupdata.Typekategori", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Typekategori");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ec64afd-f939-4987-ba17-22e3bab0da01"),
                            Beskrivelse = "livsmedium",
                            Kode = "LI"
                        },
                        new
                        {
                            Id = new Guid("f78d8f6f-89b2-4287-bb10-826d4f469ab3"),
                            Beskrivelse = "landformvariasjon",
                            Kode = "LV"
                        },
                        new
                        {
                            Id = new Guid("87bda7d2-7bd6-41a7-9e0d-216c0b836758"),
                            Beskrivelse = "marine vannmasser",
                            Kode = "MV"
                        },
                        new
                        {
                            Id = new Guid("de3acdcf-703b-41eb-810a-373eb449f95f"),
                            Beskrivelse = "primært økodiversitetsnivå",
                            Kode = "PE"
                        },
                        new
                        {
                            Id = new Guid("b0dbbb22-f713-4610-a949-1723e1932285"),
                            Beskrivelse = "sekundært økodiversitetsnivå",
                            Kode = "SE"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Lookupdata.Typekategori2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Typekategori2");

                    b.HasData(
                        new
                        {
                            Id = new Guid("63b4c148-db25-4728-b99b-b2bdde86bb32"),
                            Beskrivelse = "bremassiv",
                            Kode = "BM"
                        },
                        new
                        {
                            Id = new Guid("70ea6a19-31e4-41dc-8cd7-1cd10015d189"),
                            Beskrivelse = "elveløp",
                            Kode = "EL"
                        },
                        new
                        {
                            Id = new Guid("361536c4-9fc4-450d-97b1-f98d264475e2"),
                            Beskrivelse = "landformer i fast fjell og løsmasser",
                            Kode = "FL"
                        },
                        new
                        {
                            Id = new Guid("62e7845e-3712-4fa5-9dec-71a7b9435a92"),
                            Beskrivelse = "innsjøbasseng",
                            Kode = "IB"
                        },
                        new
                        {
                            Id = new Guid("367422ec-6b17-412d-9faa-585c0c30b68b"),
                            Beskrivelse = "landskapstype",
                            Kode = "LA"
                        },
                        new
                        {
                            Id = new Guid("3a1b3bf4-4874-4ccf-9fe4-768a3bbd614c"),
                            Beskrivelse = "natursystem",
                            Kode = "NA"
                        },
                        new
                        {
                            Id = new Guid("3b27d436-9812-42aa-a35b-c78f8741b58e"),
                            Beskrivelse = "naturkompleks",
                            Kode = "NK"
                        },
                        new
                        {
                            Id = new Guid("16ae3bdf-2e3e-41fd-bd89-d14c4a1c09d0"),
                            Beskrivelse = "torvmarksmassiv",
                            Kode = "TM"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Lookupdata.Typekategori3", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Typekategori3");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7223d990-511d-4b36-a70a-d9910256a499"),
                            Beskrivelse = "vannmassesystemer",
                            Kode = "VM"
                        },
                        new
                        {
                            Id = new Guid("24c92a7f-51fe-4899-8aaf-b3693971150f"),
                            Beskrivelse = "mark- og bunnsystemer",
                            Kode = "MB"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Lookupdata.Variabelgruppe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Variabelgruppe");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a99ea446-e8df-4b4d-a041-f8f3c14e1207"),
                            Beskrivelse = "W W",
                            Kode = "W W"
                        },
                        new
                        {
                            Id = new Guid("c52f584f-4f6c-45b6-8af5-0c8df1ec9eca"),
                            Beskrivelse = "EE elveløpsegenskaper",
                            Kode = "EE elveløpsegenskaper"
                        },
                        new
                        {
                            Id = new Guid("04754c88-f97a-40d5-8231-fb3ea9cc2869"),
                            Beskrivelse = "SB skogbruksrelaterte egeskaper",
                            Kode = "SB skogbruksrelaterte egeskaper"
                        },
                        new
                        {
                            Id = new Guid("564e10db-ef2e-48e3-bdc7-4a9f8d39752b"),
                            Beskrivelse = "DL liggende død ved (læger)",
                            Kode = "DL liggende død ved (læger)"
                        },
                        new
                        {
                            Id = new Guid("ca7b711a-e303-457a-8778-434e9a8d7466"),
                            Beskrivelse = "W artsforekomst/-mengde",
                            Kode = "W artsforekomst/-mengde"
                        },
                        new
                        {
                            Id = new Guid("5b28eec2-897c-4f6f-8fd4-576a0e2f3664"),
                            Beskrivelse = "AG artsgruppesammensetning",
                            Kode = "AG artsgruppesammensetning"
                        },
                        new
                        {
                            Id = new Guid("a10c51bb-e390-445a-94e8-b514ebb73970"),
                            Beskrivelse = "AR relativ del-artsgruppesammensetning",
                            Kode = "AR relativ del-artsgruppesammensetning"
                        },
                        new
                        {
                            Id = new Guid("8625ae4c-d982-4810-adad-148baabb9d1c"),
                            Beskrivelse = "BO naturgitte breobjekter",
                            Kode = "BO naturgitte breobjekter"
                        },
                        new
                        {
                            Id = new Guid("d56e69ef-8c8a-4db3-9050-2b09c30c6cf5"),
                            Beskrivelse = "EB elvebanker",
                            Kode = "EB elvebanker"
                        },
                        new
                        {
                            Id = new Guid("15c28f3e-e858-4c3b-8cc1-a4f2289c1ec0"),
                            Beskrivelse = "EO andre naturgitte elveløpsobjekter",
                            Kode = "EO andre naturgitte elveløpsobjekter"
                        },
                        new
                        {
                            Id = new Guid("87c91243-0880-4ccf-8d0f-d1313e3aa826"),
                            Beskrivelse = "IO naturgitte innsjøobjekter",
                            Kode = "IO naturgitte innsjøobjekter"
                        },
                        new
                        {
                            Id = new Guid("e461f3ac-c531-434c-9e6a-77982684899b"),
                            Beskrivelse = "TA torvmarksmassiv: myrsegment",
                            Kode = "TA torvmarksmassiv: myrsegment"
                        },
                        new
                        {
                            Id = new Guid("f4f94927-f09d-45ea-b217-6204d74b7183"),
                            Beskrivelse = "TB torvmarksmassiv: myrstruktur",
                            Kode = "TB torvmarksmassiv: myrstruktur"
                        },
                        new
                        {
                            Id = new Guid("46527856-dbb9-45b3-bf87-30c9bc242689"),
                            Beskrivelse = "TC torvmarksmassiv: mikrostruktur",
                            Kode = "TC torvmarksmassiv: mikrostruktur"
                        },
                        new
                        {
                            Id = new Guid("85cdbdae-f373-4944-830a-99942e3b681a"),
                            Beskrivelse = "SE skogegenskaper",
                            Kode = "SE skogegenskaper"
                        },
                        new
                        {
                            Id = new Guid("9b0713e8-bd89-4e59-a7c8-fea65aac1e0f"),
                            Beskrivelse = "IE innsjøbassengegenskaper",
                            Kode = "IE innsjøbassengegenskaper"
                        },
                        new
                        {
                            Id = new Guid("088f8c59-5208-44cb-9969-9b73cd769c72"),
                            Beskrivelse = "GE generelle egenskaper",
                            Kode = "GE generelle egenskaper"
                        },
                        new
                        {
                            Id = new Guid("60b93bef-0f4c-4b38-884c-665f894527d7"),
                            Beskrivelse = "GT generelle terrengegenskaper",
                            Kode = "GT generelle terrengegenskaper"
                        },
                        new
                        {
                            Id = new Guid("a93d07a6-8ed8-49f5-a03b-36cb3d7ae22d"),
                            Beskrivelse = "HE havegenskaper",
                            Kode = "HE havegenskaper"
                        },
                        new
                        {
                            Id = new Guid("79712a28-2240-4e8b-8f51-2e86844d3c38"),
                            Beskrivelse = "BE bremassivegenskaper",
                            Kode = "BE bremassivegenskaper"
                        },
                        new
                        {
                            Id = new Guid("c55dbb6b-3e50-408e-809f-8fe3f3d2efe6"),
                            Beskrivelse = "OE menneskeskapt objekt i elv",
                            Kode = "OE menneskeskapt objekt i elv"
                        },
                        new
                        {
                            Id = new Guid("dd40a005-33a3-4ccd-a832-52c2bb711d18"),
                            Beskrivelse = "OI menneskeskapt objekt i innsjø eller til havs",
                            Kode = "OI menneskeskapt objekt i innsjø eller til havs"
                        },
                        new
                        {
                            Id = new Guid("13a752a7-bc6f-4870-bd74-c9f4e94d2b79"),
                            Beskrivelse = "OT menneskeskapt terrestrisk objekt",
                            Kode = "OT menneskeskapt terrestrisk objekt"
                        },
                        new
                        {
                            Id = new Guid("94cf4a08-85c6-4683-a6c5-a59e8cadabd1"),
                            Beskrivelse = "SU suksesjonsrelaterte egenskaper",
                            Kode = "SU suksesjonsrelaterte egenskaper"
                        },
                        new
                        {
                            Id = new Guid("0114751d-f3ce-45eb-b076-443870b39489"),
                            Beskrivelse = "JB jordbruksrelaterte egenskaper",
                            Kode = "JB jordbruksrelaterte egenskaper"
                        },
                        new
                        {
                            Id = new Guid("829adb46-c246-461d-b2b7-e5b485b68b30"),
                            Beskrivelse = "SB skogbruksrelaterte egenskaper",
                            Kode = "SB skogbruksrelaterte egenskaper"
                        },
                        new
                        {
                            Id = new Guid("42b2d6da-b5e1-415d-9fac-b184ed19a4e5"),
                            Beskrivelse = "SB skogbruksegenskaper",
                            Kode = "SB skogbruksegenskaper"
                        },
                        new
                        {
                            Id = new Guid("a28d4c7c-0791-4060-9d78-516d3194c1e0"),
                            Beskrivelse = "DG stående død ved (gadder)",
                            Kode = "DG stående død ved (gadder)"
                        },
                        new
                        {
                            Id = new Guid("22063ae1-bc94-4dec-941d-3d010a2daf10"),
                            Beskrivelse = "DR relativ sammensetning av død ved",
                            Kode = "DR relativ sammensetning av død ved"
                        },
                        new
                        {
                            Id = new Guid("4bfb6464-e18a-4c59-9684-41bab4df8492"),
                            Beskrivelse = "TE generelle treegenskaper",
                            Kode = "TE generelle treegenskaper"
                        },
                        new
                        {
                            Id = new Guid("4efa5e5a-ba54-4a8b-bfb7-e73bc24e42b0"),
                            Beskrivelse = "TG gammelt tre",
                            Kode = "TG gammelt tre"
                        },
                        new
                        {
                            Id = new Guid("01b45ec5-66e7-45d9-af2d-f19ccda58138"),
                            Beskrivelse = "TL tre med spesielt livsmedium",
                            Kode = "TL tre med spesielt livsmedium"
                        },
                        new
                        {
                            Id = new Guid("d58d296c-31d5-4112-88e1-d5d7050091d5"),
                            Beskrivelse = "TM trær med gitt minstestørrelse",
                            Kode = "TM trær med gitt minstestørrelse"
                        },
                        new
                        {
                            Id = new Guid("829c32cd-0bb9-44bb-8787-cf80881388cb"),
                            Beskrivelse = "TS trær med gitt størrelse",
                            Kode = "TS trær med gitt størrelse"
                        },
                        new
                        {
                            Id = new Guid("20d8984b-f8d3-4d25-aca9-5c393cb24ae2"),
                            Beskrivelse = "AM artsforekomst/-mengde",
                            Kode = "AM artsforekomst/-mengde"
                        },
                        new
                        {
                            Id = new Guid("9fd78342-24b1-4305-9cf0-5655d3914c45"),
                            Beskrivelse = "FA fremmedartsegenskaper",
                            Kode = "FA fremmedartsegenskaper"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Lookupdata.Variabelkategori", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Variabelkategori");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1eeebb71-c29f-4065-a7de-205d5126b78b"),
                            Beskrivelse = "mennekebetinget",
                            Kode = "M"
                        },
                        new
                        {
                            Id = new Guid("cc0bf7f2-c01f-46ef-965f-9b6c3d454fc5"),
                            Beskrivelse = "naturgitt",
                            Kode = "N"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Lookupdata.Variabelkategori2", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Variabelkategori2");

                    b.HasData(
                        new
                        {
                            Id = new Guid("64bdb6f3-0966-40d0-96e9-deb88d3270ac"),
                            Beskrivelse = "artssammensetningsdynamikk",
                            Kode = "AD"
                        },
                        new
                        {
                            Id = new Guid("15c8dd28-c9c6-404c-a8be-b7a8ebdbea5a"),
                            Beskrivelse = "bergarter",
                            Kode = "BE"
                        },
                        new
                        {
                            Id = new Guid("de9f9a88-9efc-40c1-9b76-acf353349afc"),
                            Beskrivelse = "korttidsmiljøvariabel",
                            Kode = "KM"
                        },
                        new
                        {
                            Id = new Guid("25af7df3-0b40-4e35-a81d-a64f9a933b72"),
                            Beskrivelse = "lokal miljøvariabel",
                            Kode = "LM"
                        },
                        new
                        {
                            Id = new Guid("b3e1ee81-752b-4f3a-9269-94449db3bd18"),
                            Beskrivelse = "landform-objekter",
                            Kode = "LO"
                        },
                        new
                        {
                            Id = new Guid("704c2155-cd00-462a-941c-fa4277b3b697"),
                            Beskrivelse = "miljødynamikk",
                            Kode = "MD"
                        },
                        new
                        {
                            Id = new Guid("15483961-5c64-4e44-90c4-d39d89debf3a"),
                            Beskrivelse = "menneskeskapt objekt",
                            Kode = "MO"
                        },
                        new
                        {
                            Id = new Guid("ec46a7db-2d35-4f74-aec1-6040537a6d53"),
                            Beskrivelse = "naturgitt objekt",
                            Kode = "NO"
                        },
                        new
                        {
                            Id = new Guid("2ecf332b-f870-4255-a51f-5af6c696b575"),
                            Beskrivelse = "romlig artsfordelingsmønster",
                            Kode = "RA"
                        },
                        new
                        {
                            Id = new Guid("cc9a1c46-5883-4f55-b7bd-b0590dd3af7c"),
                            Beskrivelse = "regional miljøvariabel",
                            Kode = "RM"
                        },
                        new
                        {
                            Id = new Guid("56d69a76-c974-4d42-9062-f2b2f439d48a"),
                            Beskrivelse = "romlig strukturvariasjon",
                            Kode = "RS"
                        },
                        new
                        {
                            Id = new Guid("c1d5bb3b-c0a9-4e1d-9ccf-c0c772a11b0e"),
                            Beskrivelse = "strukturerende og funksjonelle artsgrupper",
                            Kode = "SA"
                        },
                        new
                        {
                            Id = new Guid("26f6c558-67bb-4b70-95d2-a1cff40089f3"),
                            Beskrivelse = "terrengformvariasjon",
                            Kode = "TF"
                        },
                        new
                        {
                            Id = new Guid("314f0a2c-ec2b-42c6-b109-7b8dbfa5b910"),
                            Beskrivelse = "vertikal struktur",
                            Kode = "VS"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Lookupdata.Variabeltype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Variabeltype");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a27a16c7-cccb-4e25-92f9-5b88c0b5202c"),
                            Beskrivelse = "enkel, ikke-ordnet faktorvariabel",
                            Kode = "FE"
                        },
                        new
                        {
                            Id = new Guid("397eee3e-3a4f-43e6-9c34-ab3d8cc11107"),
                            Beskrivelse = "kompleks, ikke-ordnet faktorvariabel",
                            Kode = "FK"
                        },
                        new
                        {
                            Id = new Guid("29831898-1e63-43b0-b8d8-6efea6e3747b"),
                            Beskrivelse = "enkel gradient",
                            Kode = "GE"
                        },
                        new
                        {
                            Id = new Guid("df99195e-e463-4151-9ed7-48d8edb04cbe"),
                            Beskrivelse = "kompleks gradient",
                            Kode = "GK"
                        });
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Type", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EcosystnivaaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Typekategori2Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TypekategoriId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EcosystnivaaId");

                    b.HasIndex("Typekategori2Id");

                    b.HasIndex("TypekategoriId");

                    b.HasIndex("VersionId");

                    b.ToTable("Type");
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Undertype", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GrunntypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GrunntypeId");

                    b.HasIndex("VersionId");

                    b.ToTable("Undertype");
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Grunntype", b =>
                {
                    b.HasOne("NiN3KodeAPI.Entities.Hovedtype", "Hovedtype")
                        .WithMany()
                        .HasForeignKey("HovedtypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NiN3KodeAPI.Entities.Lookupdata.Prosedyrekategori", "Prosedyrekategori")
                        .WithMany()
                        .HasForeignKey("ProsedyrekategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NiN3KodeAPI.Entities.Domene", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hovedtype");

                    b.Navigation("Prosedyrekategori");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Hovedtype", b =>
                {
                    b.HasOne("NiN3KodeAPI.Entities.Hovedtypegruppe", "Hovedtypegruppe")
                        .WithMany()
                        .HasForeignKey("HovedtypegruppeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NiN3KodeAPI.Entities.Lookupdata.Prosedyrekategori", "Prosedyrekategori")
                        .WithMany()
                        .HasForeignKey("ProsedyrekategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NiN3KodeAPI.Entities.Domene", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hovedtypegruppe");

                    b.Navigation("Prosedyrekategori");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Hovedtypegruppe", b =>
                {
                    b.HasOne("NiN3KodeAPI.Entities.Lookupdata.Typekategori2", "Typekategori2")
                        .WithMany()
                        .HasForeignKey("Typekategori2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NiN3KodeAPI.Entities.Domene", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Typekategori2");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Type", b =>
                {
                    b.HasOne("NiN3KodeAPI.Entities.Lookupdata.Ecosystnivaa", "Ecosystnivaa")
                        .WithMany()
                        .HasForeignKey("EcosystnivaaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NiN3KodeAPI.Entities.Lookupdata.Typekategori2", "Typekategori2")
                        .WithMany()
                        .HasForeignKey("Typekategori2Id");

                    b.HasOne("NiN3KodeAPI.Entities.Lookupdata.Typekategori", "Typekategori")
                        .WithMany()
                        .HasForeignKey("TypekategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NiN3KodeAPI.Entities.Domene", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ecosystnivaa");

                    b.Navigation("Typekategori");

                    b.Navigation("Typekategori2");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("NiN3KodeAPI.Entities.Undertype", b =>
                {
                    b.HasOne("NiN3KodeAPI.Entities.Grunntype", "Grunntype")
                        .WithMany()
                        .HasForeignKey("GrunntypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NiN3KodeAPI.Entities.Domene", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grunntype");

                    b.Navigation("Version");
                });
#pragma warning restore 612, 618
        }
    }
}
